"""Initial migration

Revision ID: fd5158b40399
Revises:
Create Date: 2025-12-04 18:59:54.465667

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd5158b40399"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offices",
        sa.Column("address", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offices")),
    )
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("surname", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("telegram_id", sa.String(length=16), nullable=True),
        sa.Column("telegram_id_confirmed", sa.Boolean(), nullable=False),
        sa.Column("password", sa.String(length=500), nullable=False),
        sa.Column(
            "reg_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("photo", sa.String(length=500), nullable=True),
        sa.Column(
            "role",
            sa.Enum("admin", "teacher", name="user_role"),
            server_default="teacher",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("telegram_id", name=op.f("uq_users_telegram_id")),
    )
    op.create_table(
        "audiences",
        sa.Column(
            "type",
            sa.Enum("row", "perimeter", name="audiencetype"),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("office_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["office_id"],
            ["offices.id"],
            name=op.f("fk_audiences_office_id_offices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audiences")),
    )
    op.create_table(
        "additional_hardwares",
        sa.Column("audience_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "computer",
                "tv",
                "projector",
                "printer",
                "switch",
                "router",
                "other",
                name="hardwaretype",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_functional", sa.Boolean(), nullable=False),
        sa.Column("specifications", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["audience_id"],
            ["audiences.id"],
            name=op.f("fk_additional_hardwares_audience_id_audiences"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_additional_hardwares")),
    )
    op.create_table(
        "rows",
        sa.Column("name", sa.String(length=6), nullable=False),
        sa.Column("audience_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["audience_id"],
            ["audiences.id"],
            name=op.f("fk_rows_audience_id_audiences"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rows")),
    )
    op.create_table(
        "computers",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("row_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["row_id"],
            ["rows.id"],
            name=op.f("fk_computers_row_id_rows"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_computers")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("computers")
    op.drop_table("rows")
    op.drop_table("additional_hardwares")
    op.drop_table("audiences")
    op.drop_table("users")
    op.drop_table("offices")
    # ### end Alembic commands ###
