"""Убран check для корпуса

Revision ID: 3c96c7c221eb
Revises: 3463f14a32ab
Create Date: 2025-12-15 16:53:15.005252

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "3c96c7c221eb"
down_revision: str | Sequence[str] | None = "3463f14a32ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
