"""additional_hardware перемещено в отдельную таблицу

Revision ID: 6511e879363d
Revises: d1ee3c14c92e
Create Date: 2025-10-02 18:51:48.151553

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6511e879363d"
down_revision: Union[str, Sequence[str], None] = "d1ee3c14c92e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "additional_hardwares",
        sa.Column("audience_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "tv",
                "camera",
                "projector",
                "sound_system",
                "interactive_board",
                "other",
                name="hardwaretype",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("description", sa.VARCHAR(length=255), nullable=True),
        sa.Column("is_functional", sa.Boolean(), nullable=False),
        sa.Column("specifications", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["audience_id"],
            ["audiences.id"],
            name=op.f("fk_additional_hardwares_audience_id_audiences"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_additional_hardwares")),
    )
    op.drop_column("audiences", "additional_hardware")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audiences",
        sa.Column(
            "additional_hardware",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_table("additional_hardwares")
    # ### end Alembic commands ###
