"""init

Revision ID: 626543eb530a
Revises:
Create Date: 2025-10-01 13:30:10.592877

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "626543eb530a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audiences",
        sa.Column("additional_hardware", sa.JSON(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("row", "perimeter", name="audiencetype"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audiences")),
    )
    op.create_table(
        "rows",
        sa.Column("name", sa.VARCHAR(length=6), nullable=False),
        sa.Column("audience_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["audience_id"],
            ["audiences.id"],
            name=op.f("fk_rows_audience_id_audiences"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rows")),
    )
    op.create_table(
        "computers",
        sa.Column("name", sa.VARCHAR(length=32), nullable=False),
        sa.Column("row_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["row_id"], ["rows.id"], name=op.f("fk_computers_row_id_rows")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_computers")),
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "users",
        "telegram_id_confirmed",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "users",
        "reg_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_index(
        op.f("idx_users_telegram_id_not_null"),
        table_name="users",
        postgresql_where="(telegram_id IS NOT NULL)",
    )
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.create_unique_constraint(op.f("uq_users_email"), "users", ["email"])
    op.drop_column("users", "name")
    op.drop_column("users", "surname")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "surname",
            sa.VARCHAR(length=64),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "name", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    op.create_unique_constraint(
        op.f("users_email_key"),
        "users",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_users_telegram_id_not_null"),
        "users",
        ["telegram_id"],
        unique=True,
        postgresql_where="(telegram_id IS NOT NULL)",
    )
    op.alter_column(
        "users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "users",
        "reg_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "users",
        "telegram_id_confirmed",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.drop_table("computers")
    op.drop_table("rows")
    op.drop_table("audiences")
    # ### end Alembic commands ###
