"""Добавлен этаж в сущность аудитории

Revision ID: 62e1f1be767f
Revises: 3c96c7c221eb
Create Date: 2025-12-15 17:15:51.254316

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62e1f1be767f"
down_revision: str | Sequence[str] | None = "3c96c7c221eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audiences", sa.Column("floor", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("audiences", "floor")
    # ### end Alembic commands ###
