"""Роль специалиста упразднена

Revision ID: 4341107d284f
Revises: 62e1f1be767f
Create Date: 2025-12-17 14:56:00.334596

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "4341107d284f"
down_revision: str | Sequence[str] | None = "62e1f1be767f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
