"""rows and computers ondelete=cascade

Revision ID: d1ee3c14c92e
Revises: 626543eb530a
Create Date: 2025-10-02 17:41:41.219994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d1ee3c14c92e"
down_revision: Union[str, Sequence[str], None] = "626543eb530a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_computers_row_id_rows"), "computers", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_computers_row_id_rows"),
        "computers",
        "rows",
        ["row_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_rows_audience_id_audiences"), "rows", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_rows_audience_id_audiences"),
        "rows",
        "audiences",
        ["audience_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_rows_audience_id_audiences"), "rows", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_rows_audience_id_audiences"),
        "rows",
        "audiences",
        ["audience_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_computers_row_id_rows"), "computers", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_computers_row_id_rows"),
        "computers",
        "rows",
        ["row_id"],
        ["id"],
    )
    # ### end Alembic commands ###
