"""Переход на сетку

Revision ID: 3463f14a32ab
Revises: fd5158b40399
Create Date: 2025-12-14 17:37:17.068996

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3463f14a32ab"
down_revision: Union[str, Sequence[str], None] = "fd5158b40399"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hardwares",
        sa.Column("inv_number", sa.String(length=32), nullable=True),
        sa.Column("title", sa.String(length=64), nullable=True),
        sa.Column("state", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "computer",
                "server",
                "tv",
                "projector",
                "printer",
                "switch",
                "router",
                "other",
                name="hardwaretype",
            ),
            nullable=False,
        ),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.Column("audience_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["audience_id"],
            ["audiences.id"],
            name=op.f("fk_hardwares_audience_id_audiences"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hardwares")),
    )
    op.drop_table("additional_hardwares")
    op.drop_table("computers")
    op.drop_table("rows")
    op.add_column(
        "audiences", sa.Column("width", sa.Integer(), nullable=False)
    )
    op.add_column(
        "audiences", sa.Column("height", sa.Integer(), nullable=False)
    )
    op.drop_column("audiences", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audiences",
        sa.Column(
            "type",
            postgresql.ENUM("row", "perimeter", name="audiencetype"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("audiences", "height")
    op.drop_column("audiences", "width")
    op.create_table(
        "computers",
        sa.Column(
            "name", sa.VARCHAR(length=32), autoincrement=False, nullable=False
        ),
        sa.Column("row_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("state", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "description",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["row_id"],
            ["rows.id"],
            name=op.f("fk_computers_row_id_rows"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_computers")),
    )
    op.create_table(
        "rows",
        sa.Column(
            "name", sa.VARCHAR(length=6), autoincrement=False, nullable=False
        ),
        sa.Column(
            "audience_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["audience_id"],
            ["audiences.id"],
            name=op.f("fk_rows_audience_id_audiences"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rows")),
    )
    op.create_table(
        "additional_hardwares",
        sa.Column(
            "audience_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "type",
            postgresql.ENUM(
                "tv",
                "camera",
                "projector",
                "sound_system",
                "interactive_board",
                "other",
                name="hardwaretype",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "description",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_functional", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "specifications",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["audience_id"],
            ["audiences.id"],
            name=op.f("fk_additional_hardwares_audience_id_audiences"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_additional_hardwares")),
    )
    op.drop_table("hardwares")
    # ### end Alembic commands ###
