"""Файлы для hardware 2

Revision ID: bbcb19ac50f4
Revises: cdc5cec78e5a
Create Date: 2025-12-27 13:27:49.169808

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bbcb19ac50f4"
down_revision: Union[str, Sequence[str], None] = "cdc5cec78e5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
