"""Файлы для hardware 2

Revision ID: bbcb19ac50f4
Revises: cdc5cec78e5a
Create Date: 2025-12-27 13:27:49.169808

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "bbcb19ac50f4"
down_revision: str | Sequence[str] | None = "cdc5cec78e5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
