"""Invite link role стал enum

Revision ID: 7ad241503f0c
Revises: 9f8e99ebcdaa
Create Date: 2026-04-07 19:26:57.646123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad241503f0c'
down_revision: Union[str, Sequence[str], None] = '9f8e99ebcdaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_links', sa.Column('role', sa.Enum('admin', 'teacher', name='user_role'), server_default='teacher', nullable=False))
    op.drop_column('invite_links', 'target_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_links', sa.Column('target_role', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('invite_links', 'role')
    # ### end Alembic commands ###
