"""refresh_token_hash instead of refresh_jti

Revision ID: f3b08eadf01a
Revises: aecd84374fd1
Create Date: 2026-04-13 17:30:51.327446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b08eadf01a'
down_revision: Union[str, Sequence[str], None] = 'aecd84374fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_telegram_link_tokens_user_id_users'), 'telegram_link_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('fk_telegram_link_tokens_user_id_users'), 'telegram_link_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_sessions', sa.Column('refresh_token_hash', sa.String(length=64), nullable=False))
    op.drop_index(op.f('ix_user_sessions_refresh_jti'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=False)
    op.drop_column('user_sessions', 'refresh_jti')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('refresh_jti', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_refresh_jti'), 'user_sessions', ['refresh_jti'], unique=False)
    op.drop_column('user_sessions', 'refresh_token_hash')
    op.drop_constraint(op.f('fk_telegram_link_tokens_user_id_users'), 'telegram_link_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('fk_telegram_link_tokens_user_id_users'), 'telegram_link_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
