"""Specs for some hardware

Revision ID: cd9120be41ab
Revises: 9713f8ad112f
Create Date: 2026-03-31 17:26:31.518517

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cd9120be41ab'
down_revision: str | Sequence[str] | None = '9713f8ad112f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade():
    op.add_column(
        "hardwares",
        sa.Column(
            "specs",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hardwares', 'specs')
    # ### end Alembic commands ###
