"""Hardware size, user tg_id BigInt

Revision ID: 9713f8ad112f
Revises: 90b50ff631bd
Create Date: 2026-03-30 13:19:37.196200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9713f8ad112f'
down_revision: Union[str, Sequence[str], None] = '90b50ff631bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hardwares', sa.Column('width', sa.Integer(), nullable=False, server_default="1"))
    op.add_column('hardwares', sa.Column('height', sa.Integer(), nullable=False, server_default="1"))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.BigInteger(),
               existing_nullable=True,
                postgresql_using="telegram_id::bigint")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.drop_column('hardwares', 'height')
    op.drop_column('hardwares', 'width')
    # ### end Alembic commands ###
