"""UserSession

Revision ID: 67baaa413309
Revises: ddd5ea1d70e2
Create Date: 2026-02-22 20:41:11.743691

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "67baaa413309"
down_revision: str | Sequence[str] | None = "ddd5ea1d70e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
