"""Landmarks for audiences

Revision ID: 83e7ce4a9318
Revises: cd9120be41ab
Create Date: 2026-04-05 14:13:44.222240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83e7ce4a9318'
down_revision: Union[str, Sequence[str], None] = 'cd9120be41ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audiences', sa.Column('landmarks', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb"),))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audiences', 'landmarks')
    # ### end Alembic commands ###
