"""Invite link role fix

Revision ID: 4c306f13ae9a
Revises: 7ad241503f0c
Create Date: 2026-04-07 22:15:02.814192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c306f13ae9a'
down_revision: Union[str, Sequence[str], None] = '7ad241503f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_links', sa.Column('target_role', sa.Enum('admin', 'teacher', name='user_role'), server_default='teacher', nullable=False))
    op.drop_column('invite_links', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_links', sa.Column('role', postgresql.ENUM('admin', 'technician', 'teacher', name='user_role'), server_default=sa.text("'teacher'::user_role"), autoincrement=False, nullable=False))
    op.drop_column('invite_links', 'target_role')
    # ### end Alembic commands ###
